[build]
  publish = "static"

[[headers]]
  for = "/*"

  [headers.values]
    Access-Control-Allow-Origin = "https://mycloud.rgrannell.xyz"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
